#
# Build
#

build { core 
	init 
	drivers/timer
	drivers/i2c
	test/i2c
}

create_boot_directory

#
# Generate config
#

set config {
<config verbose="yes">
	<parent-provides>
		<service name="CAP"/>
		<service name="LOG"/>
		<service name="RM"/>
		<service name="SIGNAL"/>
		<service name="IO_MEM"/>
		<service name="IRQ"/>
		<service name="ROM"/>
		<service name="RAM"/>
		<service name="IO_PORT"/>
		<service name="PD"/>
		<service name="CPU"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Timer"/></provides>
	</start>
	<start name="zynq_i2c">
		<binary name="zynq_i2c_drv" />
		<resource name="RAM" quantum="1M" />
		<provides><service name="I2C"/></provides>
	</start>
	<start name="i2c-test">
		<resource name="RAM" quantum="1M" />
		<service name="I2C"> <child name="zynq_i2c" /> </service>
		<service name="Timer"> <child name="timer" /> </service>
	</start>
</config>}

install_config $config

#
# Boot image
#

build_boot_image { 	core 
			init 
			timer
			zynq_i2c_drv
			i2c-test
}

append qemu_args " -nographic "

run_genode_until {I2C Test: done} 60
