#
# Build
#

build { core
        init
	drivers/timer
        drivers/vdma
        test/vdma
}

create_boot_directory

#
# Generate config
#

set config {
<config verbose="yes">
	<parent-provides>
		<service name="CAP"/>
		<service name="LOG"/>
		<service name="RM"/>
		<service name="SIGNAL"/>
		<service name="IO_MEM"/>
		<service name="IRQ"/>
		<service name="ROM"/>
		<service name="RAM"/>
		<service name="IO_PORT"/>
		<service name="PD"/>
		<service name="CPU"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Timer"/></provides>
	</start>
        <start name="zynq_vdma">
                <binary name="zynq_vdma_drv" />
                <resource name="RAM" quantum="1M" />
                <provides><service name="Vdma"/></provides>
                <config>
                        <vdma addr="0x43010000"/>
                        <vdma addr="0x43000000"/>
                        <vdma addr="0x43020000"/>
                </config>
	</start>
        <start name="vdma-test">
                <resource name="RAM" quantum="1M" />
                <service name="Vdma"> <child name="zynq_vdma" /> </service>
		<service name="Timer"> <child name="timer" /> </service>
	</start>
</config>}

install_config $config

#
# Boot image
#

build_boot_image { 	core
                        init
			timer
                        zynq_vdma_drv
                        vdma-test
                        ld.lib.so
                        libc.lib.so
                        libm.lib.so
                        stdcxx.lib.so
}

append qemu_args " -nographic "

run_genode_until {VDMA Test: done} 60
